services:
    api:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        container_name: url_shortener_api
        env_file:
            - ../.env.dev
        ports:
            - '8000:8000'
        volumes:
            - ../:/app
        depends_on:
            - postgres
            - redis
        command: uv run python main.py

    postgres:
        image: postgres:15
        container_name: url_shortener_postgres
        restart: always
        env_file:
            - ../.env.dev
        ports:
            - '5433:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:7
        container_name: url_shortener_redis
        restart: always
        env_file:
            - ../.env.dev
        ports:
            - '6379:6379'
        command: ['redis-server', '--appendonly', 'yes']

    tests:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        container_name: url_shortener_tests
        env_file:
            - ../.env.dev
        volumes:
            - ../:/app
        depends_on:
            - postgres
            - redis
        command: uv run pytest -q

volumes:
    pgdata:
